# Generated by Django 5.1.3 on 2024-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_species_description_alter_species_file_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.CharField(blank=True, max_length=100000, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='file_fruit',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='file_leaf',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='folder_gallery',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
