# Generated by Django 5.1.3 on 2024-11-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_species_description_alter_species_file_fruit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_fruit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
