# Generated by Django 5.1.3 on 2024-11-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_species_description_alter_species_file_fruit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='loc',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='species',
            name='user_name',
            field=models.CharField(blank=True, max_length=200),
        ),
       
    ]
