# Generated by Django 5.1.3 on 2024-11-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_alter_species_name_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_fruit',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
