# Generated by Django 5.1.3 on 2024-11-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_species_name_fruit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_leaf',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
