# Generated by Django 5.1.3 on 2024-11-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_species_name_leaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='name_fruit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
